FROM nginx:1.18-alpine AS base
ADD docker/nginx/conf.d/* /etc/nginx/conf.d/

FROM base AS development
RUN sed -i 's/localhost/project_name/g' /etc/nginx/conf.d/php-fpm.include

FROM base
ADD --chown=nginx public /var/www/public
